"""Initial schema

Revision ID: 4e5ff80e44ad
Revises: 
Create Date: 2026-09-30 11:56:38.040835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5ff80e44ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('REPORTER', 'DEVELOPER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_team', sa.String(length=255), nullable=False),
    sa.Column('owner_developer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_developer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bugs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'CLARIFYING', 'TRIAGING', 'REPRODUCED', 'ROUTED', 'CLOSED', 'DUPLICATE', name='bugstatus', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='bugseverity', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='bugpriority', native_enum=False), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clarification_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.Enum('AGENT', 'USER', name='clarificationsender', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duplicate_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('matched_bug_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['matched_bug_id'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('developer_id', sa.Uuid(), nullable=False),
    sa.Column('rating_summary', sa.Integer(), nullable=False),
    sa.Column('rating_duplicate', sa.Integer(), nullable=False),
    sa.Column('rating_component', sa.Integer(), nullable=False),
    sa.Column('rating_reproduction', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'WAITING_FOR_USER', 'COMPLETED', 'FAILED', name='triagestatus', native_enum=False), nullable=False),
    sa.Column('full_report', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('triage_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['triage_run_id'], ['triage_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_actions')
    op.drop_table('triage_runs')
    op.drop_table('feedback')
    op.drop_table('evidence')
    op.drop_table('duplicate_matches')
    op.drop_table('clarification_messages')
    op.drop_table('bugs')
    op.drop_table('components')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
